version: 2

sources:
  - name: movie_data_mage
    tables:
      - name: movie_details
      - name: movie_details__genres
      - name: movie_details__reviews__results
      - name: movie_details__similar__results
      - name: trending_movies
      - name: trending_movies__genre_ids
      - name: trending_tv_series
      - name: trending_tv_series__genre_ids
      - name: tv_series_details
      - name: tv_series_details__genres
      - name: tv_series_details__reviews__results
      - name: tv_series_details__similar__results
      - name: genres_movies
      - name: genres_tv_series
