name: "bigquery_de"

profile: "dbt_bigquery"

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

# seeds:
#   # Builds seeds into '<your_schema_name>_raw'
#   dbt_bigquery:
#     +schema: raw

models:
  bigquery_de:
    # Materialize staging models as ephemeral, and marts as tables
    staging:
      +materialized: ephemeral
    marts:
      +materialized: table

vars:
  surrogate_key_treat_nulls_as_empty_strings: true
