name: "bigquery_de"

profile: "dbt_bigquery"

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

# seeds:
#   # Builds seeds into '<your_schema_name>_raw'
#   dbt_bigquery:
#     +schema: raw

# models:
#   dbt_bigquery:
#     # Materialize staging models as views, and marts as tables
#     staging:
#       +materialized: view
#     marts:
#       +materialized: table
